.TH WHIPTAIL 1 "31 January 2007" "Whiptail Version 0.52.5"
.SH NAME
whiptail \- display dialog boxes from shell scripts
.SH SYNOPSIS
.B whiptail
[
.B \-\-title
.I title
]
[
.B \-\-backtitle
.I backtitle
]
[
.B \-\-clear
]
[
.B \-\-default\-item
.I string
]
[
.B \-\-defaultno
]
[
.B \-\-fb
]
[
.B \-\-nocancel
]
[
.B \-\-yes\-button
.I text
]
[
.B \-\-no\-button
.I text
]
[
.B \-\-ok\-button
.I text
]
[
.B \-\-cancel\-button
.I text
]
[
.B \-\-noitem
[
]
.B \-\-output\-fd
.I fd
]
[
.B \-\-separate\-output
]
[
.B \-\-scrolltext
]
[
.B \-\-topleft
]
.B box-options
.SH DESCRIPTION
.B whiptail
is a program that will let you present a variety of questions or
display messages using dialog boxes from a shell script. Currently,
these types of dialog boxes are implemented: 
.LP
.BR yes/no " box," " menu" " box," " input" " box,"
.BR message " box," " text" " box," " info" " box,"
.BR checklist " box," " radiolist" " box" " gauge" " box, and"
.BR password " box."
.SH OPTIONS
.TP
.B \-\-clear
The screen will be cleared to the
.BR "screen attribute" " on exit."
This doesn't work in an xterm (and descendants) if alternate screen
switching is enabled, because in that case slang writes to (and clears)
an alternate screen.
.TP
.B \-\-defaultno
The dialog box will open with the cursor over the 
.BR No " button."
.TP
.BI \-\-default\-item " string"
Set  the default item in a menu box.
Normally the first item in the box is the default.
.TP
\fB\-\-fb\fR, \fB\-\-fullbuttons\fR
Use full buttons. (By default, 
.B whiptail
uses compact buttons). 
.TP
.B \-\-nocancel
The dialog box won't have a 
.BR Cancel " button".
.TP
.BI \-\-yes\-button " text"
Set the text of the
.BR Yes " button."
.TP
.BI \-\-no\-button " text"
Set the text of the
.BR No " button."
.TP
.BI \-\-ok\-button " text"
Set the text of the
.BR Ok " button."
.TP
.BI \-\-cancel\-button " text"
Set the text of the
.BR Cancel " button."
.TP
.B \-\-noitem
The menu, checklist and radiolist widgets will display tags only, not
the item strings. The menu widget still needs some items specified,
but checklist and radiolist expect only tag and status.
.TP
.B \-\-notags
Don't display tags in the menu, checklist and radiolist widgets.
.TP
.BI \-\-separate\-output
For checklist widgets, output result one line at a time, with no
quoting.  This facilitates parsing by another program.
.TP
.BI \-\-output\-fd  " fd" 
Direct output to the given file descriptor.  Most 
.B whiptail
scripts
write to standard error, but  error  messages  may  also  be
written there, depending on your script.
.TP
.BI \-\-title " title"
Specifies a
.I title
string to be displayed at the top of the dialog box.
.TP
.BI \-\-backtitle " backtitle"
Specifies a
.I backtitle
string to be displayed on the backdrop, at the top of the screen.
.TP
.BI \-\-scrolltext
Force the display of a vertical scrollbar.
.TP
.BI \-\-topleft
Put window in top-left corner.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a help message and exit.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version information and exit.
.TP
.B Box Options
.TP
.BI \-\-yesno " text height width"
.RB A " yes/no" " dialog box of size"
.I height
rows by
.I width
columns will be displayed. The string specified by
.I text
is displayed inside the dialog box. If this string is too long to be fit
in one line, it will be automatically divided into multiple lines at
appropriate places. The
.I text
string may also contain the sub-string
.I
"\en"
or newline characters
.I `\en'
to control line breaking explicitly.  This dialog box is useful for
asking questions that require the user to answer either yes or no.
.RB "The dialog box has a" " Yes" " button and a " No
button, in which the user can switch between by pressing the
.IR TAB " key."
.TP
.BI \-\-msgbox " text height width"
.RB A " message" " box is very similar to a" " yes/no" " box."
The only difference between a
.B message
box and a
.B yes/no
box is that a
.B message
box has only a single
.B OK
button. You can use this dialog box to display any message you like.
After reading the message, the user can press the
.I ENTER
key so that
.B whiptail
will exit and the calling shell script can continue its operation.
.TP
.BI \-\-infobox " text height width"
.RB An " info" " box is basically a" " message" " box."
However, in this case,
.B whiptail
will exit immediately after displaying the message to the user. The
screen is not cleared when
.B whiptail
exits, so that the message will remain on the screen until the calling
shell script clears it later. This is useful when you want to inform
the user that some operations are carrying on that may require some
time to finish.
.TP
.BI \-\-inputbox " text height width [init]"
.RB "An " input " box is useful when you want to ask questions that"
require the user to input a string as the answer. If init is supplied
it is used to initialize the input string.
When inputing the
string, the
.I BACKSPACE
key can be used to correct typing errors. If the input string is longer than
the width of the dialog box, the input field will be scrolled. On exit,
the input string will be printed on
.IR stderr "."
.TP
.BI \-\-passwordbox " text height width [init]"
.RB "A " password " box is similar to an input box, except the text the user"
enters is not displayed. This is useful when prompting for passwords or other
sensitive information. Be aware that if anything is passed in "init", it
will be visible in the system's process table to casual snoopers. Also, it
is very confusing to the user to provide them with a default password they
cannot see. For these reasons, using "init" is highly discouraged.
.TP
.BI \-\-textbox " file height width"
.RB A " text" " box lets you display the contents of a text file in a"
dialog box. It is like a simple text file viewer. The user can move
through the file by using the
.IR UP/DOWN ", " PGUP/PGDN
.RI and " HOME/END" " keys available on most keyboards."
If the lines are too long to be displayed in the box, the
.I LEFT/RIGHT
keys can be used to scroll the text region horizontally. For more
convenience, forward and backward searching functions are also provided.
.IP "\fB\-\-menu \fItext height width menu-height \fR[ \fItag item \fR] \fI..."
As its name suggests, a
.B menu
box is a dialog box that can be used to present a list of choices in
the form of a menu for the user to choose. Each menu entry consists of a
.IR tag " string and an " item " string. The"
.I tag
gives the entry a name to distinguish it from the other entries in the
menu. The
.I item
is a short description of the option that the entry represents. The
user can move between the menu entries by pressing the
.I UP/DOWN
keys, the first letter of the
.I tag
as a hot-key. There are
.I menu-height
entries displayed in the menu at one time, but the menu will be
scrolled if there are more entries than that. When
.B whiptail
exits, the
.I tag
of the chosen menu entry will be printed on
.IR stderr "."
.IP "\fB\-\-checklist \fItext height width list-height \fR[ \fItag item status \fR] \fI..."
.RB "A " checklist " box is similar to a " menu " box in that there are"
multiple entries presented in the form of a menu.
You can select and deselect items using the SPACE key.  
The initial on/off state of each entry is specified by
.IR status "."
On exit, a list of the
.I tag
strings of those entries that are turned on will be printed on
.IR stderr "."

.IP "\fB\-\-radiolist \fItext height width list-height \fR [ \fItag item status \fR] \fI..."
.RB "A " radiolist " box is similar to a " menu " box.  The only difference is"
that you can indicate which entry is currently selected, by setting its
.IR status " to " on "."

.IP "\fB\-\-gauge \fItext height width percent\fR"
.RB "A " gauge " box displays a meter along the bottom of the box.
The meter indicates a percentage.  New percentages are read from
standard input, one integer per line.  The meter is updated
to reflect each new percentage.  If stdin is XXX, the first following line is
a percentage and subsequent lines up to another XXX are used for a new prompt.
The gauge exits when EOF is reached on stdin.

.SH NOTES
whiptail interprets arguments starting with a dash "\-" as being arguments.
To avoid this, and start some text in, for example, a menubox item, with a 
dash, whiptail honours the getopt convention of accepting the special
argument "\-\-" which means that all following arguments with dashes are to
be treated verbatim and not parsed as options.
.SH DIAGNOSTICS
Exit status is 0 if
.BR whiptail " is exited by pressing the " Yes " or " OK
button, and 1 if the
.BR No " or " Cancel
button is pressed. Otherwise, if errors occur inside
.B whiptail
or
.B whiptail
is exited by pressing the
.I ESC
key, the exit status is -1.
.SH AUTHOR
Based on the man page for dialog(1) by:
.LP
Savio Lam (lam836@cs.cuhk.hk) - version 0.3
.LP
Stuart Herbert (S.Herbert@sheffield.ac.uk) - patch for version 0.4
.LP
Modifications for whiptail by:
.LP
Enrique Zanardi (ezanard@debian.org)
.LP
Alastair McKinstry (mckinstry@debian.org)
